spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gps?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 60s

    index:
      number-of-shards: 1
      number-of-replicas: 0

  jackson:
    serialization:
      fail-on-empty-beans: false



logging:
  level:
    root : INFO
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.data.elasticsearch.client: error

    org.elasticsearch: error
    gps.base.ElasticSearchService.GymSyncService: error

    gps.base: debug


server:
  port: 8080
  servlet:
    context-path: /api