spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            client-name: Google
            scope:
              - email
              - profile
              - openid
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


sso:
  token:
    secret: ${SSO_TOKEN_SECRET}
    expiration: ${SSO_TOKEN_EXPIRATION}
  session:
    timeout: ${SSO_SESSION_TIMEOUT:1800}
  cors:
    allowed-origin:
      - http://localhost:8080
      - http://localhost:3000
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers:
      - Authorization
      - Content-Type
    max-age: 3600
  security:
    public-paths:
      - /api/public/**
      - /oauth2/**
      - /login/**
      - /auth/**
      - /error
    protected-paths:
      - /api/protected/**
      - /api/private/**