### 회원가입
# @no-cookie-jar
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "mid": "testuser",
  "mPassword": "password123",
  "name" : "Moon",
  "email" : "test@naver.com",
  "age" : "23" ,
  "sex" : "남성"
}